export const plants = [
    {
        name: 'Pacific Trillium',
        image: './assets/pacific-trillium.png',
        phylum: 'Tracheophyta',
        class: 'Liliopsida',
        order: 'Liliales',
        family: 'Melanthiaceae',
        genus: 'Trillium',
        found: ['Oregon', 'California', 'Montana'],
    },
    {
        name: 'Western Sword Fern',
        image: './assets/western-sword-fern.png',
        phylum: 'Tracheophyta',
        class: 'Polypodiopsida',
        order: 'Polypodiales',
        family: 'Dryopteridaceae',
        genus: 'Polystichum',
        found: ['Washington', 'Oregon', 'California'],
    },
    {
        name: 'Salal',
        image: './assets/salal.png',
        phylum: 'Tracheophyta',
        class: 'Magnoliopsida',
        order: 'Ericales',
        family: 'Ericaceae',
        genus: 'Gaultheria',
        found: ['Alaska', 'Washington', 'Oregon'],
    },
];